<<<<<<< HEAD
#framework:
=======
framework:
>>>>>>> 7eb143b6bcdecae3840eabb8b204d9becb3fdc98
   # notifier:
        #chatter_transports:
        #    slack: '%env(SLACK_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        #texter_transports:
        #    twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
<<<<<<< HEAD
        #channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
           # urgent: ['email']
            #high: ['email']
            #medium: ['email']
            #low: ['email']
        #admin_recipients:
           # - { email: admin@example.com }
=======
       # channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
        #    urgent: ['email']
        #    high: ['email']
        #    medium: ['email']
        #    low: ['email']
        #admin_recipients:
         #   - { email: admin@example.com }
>>>>>>> 7eb143b6bcdecae3840eabb8b204d9becb3fdc98
